package com.mycompany.fa2;
import com.mycompany.fa2.Add_A_Task;
import com.mycompany.fa2.TaskDataBase;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

import java.util.ArrayList;

/**
 *
 * @author sjanr
 */
public class Add_A_Task extends javax.swing.JFrame {
   private ArrayList<TaskDataBase> taskList;
     private TaskManager taskOrganiser;
       
    // Connection to the SQLite database
    private Connection connection;
    
    
    
    /**
     * Creates new form AddTask
     */
    public Add_A_Task(TaskManager taskOrganiser, ArrayList<TaskDataBase> taskList) {
        initComponents();
        this.taskOrganiser = taskOrganiser; // Initialize taskOrganiser
        this.taskList = taskList;
      
        TaskName_TextField.setText("");
        DueDate_TextField.setText("");
        Category_TextField.setText("");
        Description_TextField.setText("");
        CompStatus_TextField.setText(""); 
        
         connectToDatabase("jdbc:sqlite:C:\\Users\\sjanr\\Desktop\\Oracle\\sqlite-tools\\sqlite-tools\\task.db");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Add_Button = new javax.swing.JButton();
        Cancel_Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TaskName_TextField = new javax.swing.JTextField();
        DueDate_TextField = new javax.swing.JTextField();
        Category_TextField = new javax.swing.JTextField();
        Description_TextField = new javax.swing.JTextField();
        CompStatus_TextField = new javax.swing.JTextField();
        Clear_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add A Task");
        setBackground(java.awt.Color.black);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        Add_Button.setBackground(new java.awt.Color(51, 255, 102));
        Add_Button.setForeground(new java.awt.Color(0, 0, 0));
        Add_Button.setText("ADD");
        Add_Button.setBorder(null);
        Add_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_ButtonActionPerformed(evt);
            }
        });

        Cancel_Button.setBackground(new java.awt.Color(51, 153, 255));
        Cancel_Button.setForeground(new java.awt.Color(0, 0, 0));
        Cancel_Button.setText("CANCEL");
        Cancel_Button.setBorder(null);
        Cancel_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel_ButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Task");

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Task Name:");

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Due Date:");

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Catagory:");

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Description:");

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Completion Status:");

        TaskName_TextField.setBackground(new java.awt.Color(255, 255, 255));
        TaskName_TextField.setForeground(new java.awt.Color(0, 0, 0));
        TaskName_TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        TaskName_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaskName_TextFieldActionPerformed(evt);
            }
        });

        DueDate_TextField.setBackground(new java.awt.Color(255, 255, 255));
        DueDate_TextField.setForeground(new java.awt.Color(0, 0, 0));
        DueDate_TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        DueDate_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DueDate_TextFieldActionPerformed(evt);
            }
        });

        Category_TextField.setBackground(new java.awt.Color(255, 255, 255));
        Category_TextField.setForeground(new java.awt.Color(0, 0, 0));
        Category_TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Category_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Category_TextFieldActionPerformed(evt);
            }
        });

        Description_TextField.setBackground(new java.awt.Color(255, 255, 255));
        Description_TextField.setForeground(new java.awt.Color(0, 0, 0));
        Description_TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Description_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Description_TextFieldActionPerformed(evt);
            }
        });

        CompStatus_TextField.setBackground(new java.awt.Color(255, 255, 255));
        CompStatus_TextField.setForeground(new java.awt.Color(0, 0, 0));
        CompStatus_TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        CompStatus_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompStatus_TextFieldActionPerformed(evt);
            }
        });

        Clear_Button.setBackground(new java.awt.Color(255, 51, 51));
        Clear_Button.setForeground(new java.awt.Color(0, 0, 0));
        Clear_Button.setText("CLEAR");
        Clear_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Description_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Category_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(126, 126, 126))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DueDate_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TaskName_TextField)
                                .addComponent(CompStatus_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)))))
                .addGap(0, 58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(153, 153, 153))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Add_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Cancel_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Clear_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TaskName_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DueDate_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Category_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Description_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CompStatus_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cancel_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Clear_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //taskname
    private void TaskName_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaskName_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TaskName_TextFieldActionPerformed
        

//add button 
    private void Add_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_ButtonActionPerformed
        // TODO add your handling code here:
    String taskName = TaskName_TextField.getText();
    String dueDate = DueDate_TextField.getText();
    String category = Category_TextField.getText();
    String description = Description_TextField.getText();
    String completionStatus = CompStatus_TextField.getText();

    TaskDataBase newTask = new TaskDataBase(taskName, dueDate, category, description, completionStatus);
    taskList.add(newTask);

    // Update the task table in the TaskManager frame
    taskOrganiser.updateTaskTable();
    
      // Insert the task into the SQLite database
        insertTaskIntoDatabase(newTask);
    
    taskOrganiser.setVisible(true);
    this.dispose(); // Close the Add_A_Task frame
        
    }//GEN-LAST:event_Add_ButtonActionPerformed

    private void Cancel_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel_ButtonActionPerformed
    // Close the Add_A_Task frame and show the TaskManager frame
    taskOrganiser.setVisible(true); // Show the TaskManager frame
    this.dispose(); // Close the Add_A_Task frame
    }//GEN-LAST:event_Cancel_ButtonActionPerformed
    
    private void DueDate_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DueDate_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DueDate_TextFieldActionPerformed
    
    private void Category_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Category_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Category_TextFieldActionPerformed
    
    private void Description_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Description_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Description_TextFieldActionPerformed

    private void CompStatus_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompStatus_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CompStatus_TextFieldActionPerformed

    private void Clear_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear_ButtonActionPerformed
        // Clear the text fields
    TaskName_TextField.setText("");
    DueDate_TextField.setText("");
    Category_TextField.setText("");
    Description_TextField.setText("");
    CompStatus_TextField.setText("");
    }//GEN-LAST:event_Clear_ButtonActionPerformed
    
    private void connectToDatabase(String connStr) {
        try {
            String ConnStr = "jdbc:sqlite:C:\\Users\\sjanr\\Desktop\\Oracle\\sqlite-tools\\sqlite-tools\\task.db";
            Class.forName("org.sqlite.JDBC");
            connection = DriverManager.getConnection(connStr);
        } catch (SQLException e) {
            e.printStackTrace();
            
        }catch(ClassNotFoundException e)
        {
         e.printStackTrace();
        }
    }
   private void insertTaskIntoDatabase(TaskDataBase task) {
    PreparedStatement preparedStatement = null;

    try {
        String sql = "INSERT INTO Task (Task, Date, Category, Description, Completion) VALUES (?, ?, ?, ?, ?)";

        preparedStatement = connection.prepareStatement(sql);

        // Set the values for the placeholders in the SQL statement
        preparedStatement.setString(1, task.getTaskName());
        preparedStatement.setString(2, task.getDueDate());
        preparedStatement.setString(3, task.getCategory());
        preparedStatement.setString(4, task.getDescription());
        preparedStatement.setString(5, task.isCompletionStatus());

        // Execute the INSERT statement
        preparedStatement.executeUpdate();
    } catch (SQLException e) {
        e.printStackTrace();
    } finally {
        try {
            if (preparedStatement != null) {
                preparedStatement.close();
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
         try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(Add_A_Task.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(Add_A_Task.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(Add_A_Task.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(Add_A_Task.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
         java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            TaskManager taskOrganiser = new TaskManager();
            taskOrganiser.setVisible(true); // Show the TaskManager frame

            // Now you can open the Add_A_Task frame using the getter method
            taskOrganiser.getAddTaskFrame().setVisible(true);
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Button;
    private javax.swing.JButton Cancel_Button;
    private javax.swing.JTextField Category_TextField;
    private javax.swing.JButton Clear_Button;
    private javax.swing.JTextField CompStatus_TextField;
    private javax.swing.JTextField Description_TextField;
    private javax.swing.JTextField DueDate_TextField;
    private javax.swing.JTextField TaskName_TextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
